# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.cps_cpp <- function(cpsMethod, prob, x, bucketSize, method, eps) {
    .Call('_BalancedSampling_cps_cpp', PACKAGE = 'BalancedSampling', cpsMethod, prob, x, bucketSize, method, eps)
}

.cps_random_cpp <- function(prob, x, random, bucketSize, method, eps) {
    .Call('_BalancedSampling_cps_random_cpp', PACKAGE = 'BalancedSampling', prob, x, random, bucketSize, method, eps)
}

.cube_cpp <- function(prob, x, eps) {
    .Call('_BalancedSampling_cube_cpp', PACKAGE = 'BalancedSampling', prob, x, eps)
}

.lcube_cpp <- function(prob, xbal, xspread, bucketSize, method, eps) {
    .Call('_BalancedSampling_lcube_cpp', PACKAGE = 'BalancedSampling', prob, xbal, xspread, bucketSize, method, eps)
}

.cube_stratified_cpp <- function(prob, x, strata, eps) {
    .Call('_BalancedSampling_cube_stratified_cpp', PACKAGE = 'BalancedSampling', prob, x, strata, eps)
}

.lcube_stratified_cpp <- function(prob, xbalance, xspread, strata, bucketSize, method, eps) {
    .Call('_BalancedSampling_lcube_stratified_cpp', PACKAGE = 'BalancedSampling', prob, xbalance, xspread, strata, bucketSize, method, eps)
}

.getpps_cpp <- function(x, n) {
    .Call('_BalancedSampling_getpps_cpp', PACKAGE = 'BalancedSampling', x, n)
}

.hlpm2_cpp <- function(prob, x, sizes, bucketSize, method, eps) {
    .Call('_BalancedSampling_hlpm2_cpp', PACKAGE = 'BalancedSampling', prob, x, sizes, bucketSize, method, eps)
}

.lpm_cpp <- function(lpMethod, prob, x, bucketSize, method, eps) {
    .Call('_BalancedSampling_lpm_cpp', PACKAGE = 'BalancedSampling', lpMethod, prob, x, bucketSize, method, eps)
}

.lpm_int_cpp <- function(lpMethod, n, x, bucketSize, method) {
    .Call('_BalancedSampling_lpm_int_cpp', PACKAGE = 'BalancedSampling', lpMethod, n, x, bucketSize, method)
}

.rpm_cpp <- function(prob, eps) {
    .Call('_BalancedSampling_rpm_cpp', PACKAGE = 'BalancedSampling', prob, eps)
}

.spm_cpp <- function(prob, eps) {
    .Call('_BalancedSampling_spm_cpp', PACKAGE = 'BalancedSampling', prob, eps)
}

.sb_sumofsquares_cpp <- function(x, sample, bucketSize, method) {
    .Call('_BalancedSampling_sb_sumofsquares_cpp', PACKAGE = 'BalancedSampling', x, sample, bucketSize, method)
}

.sb_voronoi_cpp <- function(prob, x, sample, bucketSize, method) {
    .Call('_BalancedSampling_sb_voronoi_cpp', PACKAGE = 'BalancedSampling', prob, x, sample, bucketSize, method)
}

.vsb0_cpp <- function(probs, ys, xs, bucketSize, method) {
    .Call('_BalancedSampling_vsb0_cpp', PACKAGE = 'BalancedSampling', probs, ys, xs, bucketSize, method)
}

.vsbn_cpp <- function(probs, ys, xs, n, bucketSize, method) {
    .Call('_BalancedSampling_vsbn_cpp', PACKAGE = 'BalancedSampling', probs, ys, xs, n, bucketSize, method)
}

