# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.cube_stratified_cpp <- function(prob, x, strata, eps) {
    .Call('_BalancedSampling_cube_stratified_cpp', PACKAGE = 'BalancedSampling', prob, x, strata, eps)
}

.cube_cpp <- function(prob, x, eps) {
    .Call('_BalancedSampling_cube_cpp', PACKAGE = 'BalancedSampling', prob, x, eps)
}

.cube_fast_cpp <- function(prob, x, eps) {
    .Call('_BalancedSampling_cube_fast_cpp', PACKAGE = 'BalancedSampling', prob, x, eps)
}

.getpps_cpp <- function(x, n) {
    .Call('_BalancedSampling_getpps_cpp', PACKAGE = 'BalancedSampling', x, n)
}

.hlpm2_cpp <- function(prob, x, sizes, bucketSize, method, eps) {
    .Call('_BalancedSampling_hlpm2_cpp', PACKAGE = 'BalancedSampling', prob, x, sizes, bucketSize, method, eps)
}

lcps <- function(prob, x) {
    .Call('_BalancedSampling_lcps', PACKAGE = 'BalancedSampling', prob, x)
}

.lcube_stratified_cpp <- function(prob, xbal, xspread, strata, bucketSize, method, eps) {
    .Call('_BalancedSampling_lcube_stratified_cpp', PACKAGE = 'BalancedSampling', prob, xbal, xspread, strata, bucketSize, method, eps)
}

.lcube_cpp <- function(prob, xbal, xspread, bucketSize, method, eps) {
    .Call('_BalancedSampling_lcube_cpp', PACKAGE = 'BalancedSampling', prob, xbal, xspread, bucketSize, method, eps)
}

.lpm1_search_cpp <- function(prob, x, bucketSize, method, eps) {
    .Call('_BalancedSampling_lpm1_search_cpp', PACKAGE = 'BalancedSampling', prob, x, bucketSize, method, eps)
}

.lpm1_cpp <- function(prob, x, bucketSize, method, eps) {
    .Call('_BalancedSampling_lpm1_cpp', PACKAGE = 'BalancedSampling', prob, x, bucketSize, method, eps)
}

.lpm2_int_cpp <- function(n, x, bucketSize, method) {
    .Call('_BalancedSampling_lpm2_int_cpp', PACKAGE = 'BalancedSampling', n, x, bucketSize, method)
}

.lpm2_cpp <- function(prob, x, bucketSize, method, eps) {
    .Call('_BalancedSampling_lpm2_cpp', PACKAGE = 'BalancedSampling', prob, x, bucketSize, method, eps)
}

.rpm_cpp <- function(prob, eps) {
    .Call('_BalancedSampling_rpm_cpp', PACKAGE = 'BalancedSampling', prob, eps)
}

.sb_sumofsquares_cpp <- function(x, sample, bucketSize, method) {
    .Call('_BalancedSampling_sb_sumofsquares_cpp', PACKAGE = 'BalancedSampling', x, sample, bucketSize, method)
}

.sb_voronoi_cpp <- function(prob, x, sample, bucketSize, method) {
    .Call('_BalancedSampling_sb_voronoi_cpp', PACKAGE = 'BalancedSampling', prob, x, sample, bucketSize, method)
}

.scps_coord_cpp <- function(prob, x, random, bucketSize, method, eps) {
    .Call('_BalancedSampling_scps_coord_cpp', PACKAGE = 'BalancedSampling', prob, x, random, bucketSize, method, eps)
}

.scps_cpp <- function(prob, x, bucketSize, method, eps) {
    .Call('_BalancedSampling_scps_cpp', PACKAGE = 'BalancedSampling', prob, x, bucketSize, method, eps)
}

.spm_cpp <- function(prob, eps) {
    .Call('_BalancedSampling_spm_cpp', PACKAGE = 'BalancedSampling', prob, eps)
}

.vsb0_cpp <- function(probs, ys, xs, bucketSize, method) {
    .Call('_BalancedSampling_vsb0_cpp', PACKAGE = 'BalancedSampling', probs, ys, xs, bucketSize, method)
}

.vsbn_cpp <- function(probs, ys, xs, n, bucketSize, method) {
    .Call('_BalancedSampling_vsbn_cpp', PACKAGE = 'BalancedSampling', probs, ys, xs, n, bucketSize, method)
}

