# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cube <- function(prob, Xbal) {
    .Call('_BalancedSampling_cube', PACKAGE = 'BalancedSampling', prob, Xbal)
}

lcube <- function(prob, Xspread, Xbal) {
    .Call('_BalancedSampling_lcube', PACKAGE = 'BalancedSampling', prob, Xspread, Xbal)
}

flightphase <- function(prob, Xbal) {
    .Call('_BalancedSampling_flightphase', PACKAGE = 'BalancedSampling', prob, Xbal)
}

landingphase <- function(prob, probflight, Xbal) {
    .Call('_BalancedSampling_landingphase', PACKAGE = 'BalancedSampling', prob, probflight, Xbal)
}

lcubeflightphase <- function(prob, Xspread, Xbal) {
    .Call('_BalancedSampling_lcubeflightphase', PACKAGE = 'BalancedSampling', prob, Xspread, Xbal)
}

lcubelandingphase <- function(prob, probflight, Xspread, Xbal) {
    .Call('_BalancedSampling_lcubelandingphase', PACKAGE = 'BalancedSampling', prob, probflight, Xspread, Xbal)
}

cubestratified <- function(prob, Xbal, integerStrata) {
    .Call('_BalancedSampling_cubestratified', PACKAGE = 'BalancedSampling', prob, Xbal, integerStrata)
}

lcubestratified <- function(prob, Xspread, Xbal, integerStrata) {
    .Call('_BalancedSampling_lcubestratified', PACKAGE = 'BalancedSampling', prob, Xspread, Xbal, integerStrata)
}

.hlpm2_cpp <- function(prob, x, sizes, bucketSize, method, eps) {
    .Call('_BalancedSampling_hlpm2_cpp', PACKAGE = 'BalancedSampling', prob, x, sizes, bucketSize, method, eps)
}

lcps <- function(prob, x) {
    .Call('_BalancedSampling_lcps', PACKAGE = 'BalancedSampling', prob, x)
}

lpm <- function(prob, x, h) {
    .Call('_BalancedSampling_lpm', PACKAGE = 'BalancedSampling', prob, x, h)
}

.lpm1_search_cpp <- function(prob, x, bucketSize, method, eps) {
    .Call('_BalancedSampling_lpm1_search_cpp', PACKAGE = 'BalancedSampling', prob, x, bucketSize, method, eps)
}

.lpm1_cpp <- function(prob, x, bucketSize, method, eps) {
    .Call('_BalancedSampling_lpm1_cpp', PACKAGE = 'BalancedSampling', prob, x, bucketSize, method, eps)
}

.lpm2_int_cpp <- function(n, x, bucketSize, method) {
    .Call('_BalancedSampling_lpm2_int_cpp', PACKAGE = 'BalancedSampling', n, x, bucketSize, method)
}

.lpm2_cpp <- function(prob, x, bucketSize, method, eps) {
    .Call('_BalancedSampling_lpm2_cpp', PACKAGE = 'BalancedSampling', prob, x, bucketSize, method, eps)
}

.rpm_cpp <- function(prob, eps) {
    .Call('_BalancedSampling_rpm_cpp', PACKAGE = 'BalancedSampling', prob, eps)
}

.sb_sumofsquares_cpp <- function(x, sample, bucketSize, method) {
    .Call('_BalancedSampling_sb_sumofsquares_cpp', PACKAGE = 'BalancedSampling', x, sample, bucketSize, method)
}

.sb_voronoi_cpp <- function(prob, x, sample, bucketSize, method) {
    .Call('_BalancedSampling_sb_voronoi_cpp', PACKAGE = 'BalancedSampling', prob, x, sample, bucketSize, method)
}

.scps_cpp <- function(prob, x, bucketSize, method, eps) {
    .Call('_BalancedSampling_scps_cpp', PACKAGE = 'BalancedSampling', prob, x, bucketSize, method, eps)
}

.scps_coord_cpp <- function(prob, x, random, bucketSize, method, eps) {
    .Call('_BalancedSampling_scps_coord_cpp', PACKAGE = 'BalancedSampling', prob, x, random, bucketSize, method, eps)
}

.spm_cpp <- function(prob, eps) {
    .Call('_BalancedSampling_spm_cpp', PACKAGE = 'BalancedSampling', prob, eps)
}

vsb <- function(probs, ys, xs) {
    .Call('_BalancedSampling_vsb', PACKAGE = 'BalancedSampling', probs, ys, xs)
}

